;-----------------------------------------------------------------------
;
; Retrodev SDK -- CPC premixed (reverse order) palette colours.
;
; Purpose: SDK module.
;
; (c) TLOTB 2026
;
;-----------------------------------------------------------------------

ifndef __cpc_palette_premixed_asm__
__cpc_palette_premixed_asm__ equ 1

        ;
        ; Require macros.ga.asm
        ;
        include "macros.ga.asm"

        ; GA_SetPalettePremixedRev -- set N pens from a reversed table of pre-mixed GA colour bytes.
        ;
        ; Identical to GA_SetPalettePremixed but the table is stored highest-pen-first so C
        ; doubles as both the loop counter and the pen index, eliminating the separate pen
        ; register (A) and saving 4 T per pen.
        ;
        ; Table layout: pen C-1 first, pen 0 last (reversed relative to GA_SetPalettePremixed).
        ; Example for 16 pens: table[0]=colour for pen 15, table[15]=colour for pen 0.
        ;
        ; Use this when the table is under your control (e.g. generated by a custom exporter
        ; with reversed pen order) and the 4 T/pen saving matters.
        ; For standard low-to-high tables use GA_SetPalettePremixed instead.
        ;
        ; Entry:
        ;   HL = pointer to reversed table of pre-mixed GA colour bytes (highest pen first)
        ;   C  = index of the first (highest) pen to set; also the total pen count
        ;        e.g. C=16 sets pens 16..0 (border + all 16 inks), C=15 sets pens 15..0
        ; Exit:  pens C..0 written to the Gate Array
        ; Destroys: AF, BC, HL  Preserves: DE, IX, IY
        ;
        ; Speed (4 MHz Z80, T-states per iteration):
        ;   out (c),c    = 12  (select pen C -- C is pen index and counter simultaneously)
        ;   outi         = 16  (OUT (BC),(HL++); B-- -- write colour byte, advance table)
        ;   inc b        =  4  (restore B to GA_PORT_CMD_B after outi's implicit dec b)
        ;   dec c        =  4  (C-- = next pen index downward and loop counter)
        ;   jr nz        = 12  (loop -- 7 T on final iteration)
        ;                ----
        ;                 48 T per iteration (43 T on last)
        ;
        ; For 16 pens: setup(~14 T) + 15*48 + 43 = 777 T ~ 194 us  (vs 845 T for GA_SetPalettePremixed)
        GA_SetPalettePremixedRev:
                ld b,GA_PORT_CMD_B	; B = &7F -- GA port high byte, held for the entire loop
        .loop:
                out (c),c		; send pen-select command: pen index = C (GA_CMD_PEN_SELECT | C, bits 7-6 = 00)
                outi			; OUT (BC),(HL++); B-- -- send pre-mixed colour byte, advance table
                inc b			; restore B to GA_PORT_CMD_B after outi's implicit dec b
                dec c			; C-- = next pen index downward; also loop counter (Z set when done)
                jr nz,.loop		; continue until pen 0 is written (C wraps to 0 after pen 0)
                ret
endif
